apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata: null
name: cd-blog-cicd
description: CICD Application pipeline
serialPipeline: null
stages:
  - targetId: dev
    profiles: []
  - targetId: prod
    profiles: []
---
 
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
name: dev
description: development cluster
gkeCluster:
 
project: anjali-cicd
cluster: dev
location: us-central1
 
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
name: prod
description: production cluster
gkeCluster:
 
project: anjali-cicd
cluster: prod
location: us-central1